name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python deps
        run: pip install black flake8

      - name: Lint
        uses: wearerequired/lint-action@v2.1.0
        with:
          black: true
          flake8: true
