name: Python Lint
on: [push]
jobs:
  Python-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Python Lint
        uses: ricardochaves/python-lint@v1.3.0
